### ISSUE TITLE
Incompatibility with Inventory Pause

### ISSUE THREAD

**Issue by ChromaPIE** [stashymane/extra-sounds#10]
Inventory Pause is a mod that pauses the game when the inventory GUI is opened, and maybe this kind of pause is blocking all Extra Sounds from being normally triggered, the sounds is not played until the GUI is closed. It doesn't affect other GUIs like furnaces', crafting tables' since their GUIs don't pause the game.

Versions before 1.3.0 worked fine with InvPause.

**Comment by stashymane** [comment]
This is caused due to me playing sounds only on the next tick to resolve a rare crash. I'll take a look on what I can do to work around  this again
