### ISSUE TITLE
Crash / Fail to boot with Biome Makeover

### ISSUE THREAD

**Issue by itsNordLord** [stashymane/extra-sounds#11]
**Versions** / **Installed Mods**
Biome Makeover `biome-makeover-1.16.5-1.3.8`
Cloth Config `cloth-config-4.11.26-fabric`
ExtraSounds `extra-sounds-1.4.0` and `1.3.1`
Fabric API `fabric-api-0.34.2+1.16`

**Log**
[latest.log](https://github.com/stashymane/extra-sounds/files/6542761/latest.log)
There is no crashlog in `crash-reports`

**Extra**
Game fails to launch entirely, log provides very little info. Crash exists in heavy modpacks as well as with running dependencies only, removing either mod allows the game to launch as normal.

**Comment by stashymane** [comment]
Fixed for the next release - you may try [this build](https://github.com/stashymane/extra-sounds/actions/runs/878788277) to have it working until then.
