### ISSUE TITLE
Could not find required mod: extrasounds requires {cloth-config2 @ [>=4.11]}

### ISSUE THREAD

**Issue by JaxSie** [stashymane/extra-sounds#14]
unable to load in :(
![Screenshot 2021-08-18 131316](https://user-images.githubusercontent.com/89121131/129841035-bb5f918f-8a47-4d3a-8f24-95e09894feaf.png)

**Comment by stashymane** [comment]
Is [Cloth Config](https://www.curseforge.com/minecraft/mc-mods/cloth-config) installed?

**Comment by JaxSie** [comment]
> Is [Cloth Config](https://www.curseforge.com/minecraft/mc-mods/cloth-config) installed?

thats whyyy... thx
