### ISSUE TITLE
Item spreading sound crash

### ISSUE THREAD

**Issue by deci-chan** [stashymane/extra-sounds#2]
When spreading an entire (64) stack of items across the inventory while the inventory place sound is set to 0.2 or higher, the game crashes.

Crash report:
https://pastebin.com/RSap9Nim

**Comment by stashymane** [comment]
Unable to reproduce, seems like another mod is trying to change the inventory while ExtraSounds is still reading from it.
As a workaround, I tried moving when the click sound is played - can you try adding [this build of the mod](https://github.com/stashymane/extra-sounds/actions/runs/816975023) to see whether it still happens?

**Comment by stashymane** [comment]
Should be fixed by 1.1.
