### ISSUE TITLE
Possible errie sound effect related when interacting with the world

### ISSUE THREAD

**Issue by 103Sakamoto** [stashymane/extra-sounds#22]
I just installed your mod today and when I play with friends, we can both hear some creepy sound like zombile mumbling in distance when we were busy with all sorts of stuff. Yet when standing idly by without doing anything, the sound disappeared. Since this is the only mod we installed today, I disabled the mod to make a comparation. In the first few minutes everything is fine , but soon my friends could hear the sound again as soon as he interact with the world (mouse clicking), while everything is fine with me. Wonder if you could take a look at this.

**Comment by stashymane** [comment]
What Minecraft version are you on?
I suspect this is the status effect sound malfunctioning, it should go away when you set the volume of effects in the sound options to 0.

**Comment by stashymane** [comment]
I keep closing these accidentally :)

**Comment by 103Sakamoto** [comment]
I'm on 1.17.1. I'll try if this works.

**Comment by 103Sakamoto** [comment]
Yes, issues go away by setting the effect volume to 0.

**Comment by stashymane** [comment]
Can you perhaps also update me with your mod list? I did not experience any issues with my own setup as of yet, may be an incompatibility.

**Comment by 103Sakamoto** [comment]
Sure thing, though I suspect it may related to soundphysics-fabric-1.17.1-1.0.1
Here's the full list:

[1.17.1][Fabric]+RPG-HUD-3.9.1.jar
3dSkinLayers-Fabric-1.2.1.jar
Adorn-2.2.0+1.17.1-fabric.jar
appleskin-fabric-mc1.17-2.1.3.jar
architectury-2.6.35.jar
balm-fabric-1.3.0+0.jar
BetterDungeons-Fabric-1.17-1.0.2.jar
betterf3-1.1.5+1.17.jar
BetterMineshafts-Fabric-1.17-1.0.1.jar
BetterStrongholds-Fabric-1.17-1.1.2.jar
can-i-mine-this-block-1.1.0.jar
cleancut-1.17-4.0-fabric.jar
cloth-api-2.0.54.jar
cloth-config-5.0.38-fabric.jar
Clumps-fabric-1.17.1-7.0.10.jar
Couplings-1.5.1+1.17.jar
cullleaves-2.3.2.jar
CustomSkinLoader_Fabric-14.13-SNAPSHOT-301.jar
dynamic-fps-2.0.6.jar
eating-animation-1.2.jar
enchantment-lore-1.2.1+MC1.17.1.jar
enhancedblockentities-0.5+1.17.jar
entity-banners-1.0.2-BETA+1.17.jar
EntityCulling-Fabric-1.3.3.jar
extrasounds-2.0.0+1.17.jar
fabric-api-0.42.1+1.17.jar
fabric-language-kotlin-1.6.5+kotlin.1.5.31.jar
FallingTree-1.17.1-2.14.3.jar
graves-1.1.3b+1.17.1.jar
hookshot-r22.jar
IKnowWhatImDoing-4.0.0-forge.jar
IngameIME-fabric-1.17-pre5-1.6.4.jar
InventoryProfilesNext-fabric-1.17-1.1.1.jar
iris-and-sodium-mc1.17-1.1.2+build.9.jar
itemscroller-fabric-1.17.1-0.15.0-dev.20210707.005506.jar
lithium-fabric-mc1.17.1-0.7.5.jar
malilib-fabric-1.17.1-0.10.0-dev.26.jar
modmenu-2.0.14.jar
mostructures-1.3.0-pre1-1.17.1-fabric.jar
MouseTweaks-fabric-mc1.17.1-2.15.jar
npc-variety-1.17.0-2.2.0.jar
physics-mod-2.5.15-mc-1.17.1-fabric.jar
repurposed_structures_fabric-2.5.3+1.17.1.jar
RoughlyEnoughItems-6.1.319.jar
smoothboot-fabric-1.16.5-1.6.0.jar
soundphysics-fabric-1.17.1-1.0.1.jar
spark-fabric.jar
travelers-backpack-1.17.1-6.0.0.jar
traverse-4.0.0.jar
tweakeroo-fabric-1.17.1-0.10.0-dev.20210710.155746.jar
visuality-mc1.17.1-0.3.0.jar
voicechat-fabric-1.17.1-1.1.9.jar
waystones-fabric-8.1.1+0.jar
wthit-fabric-3.10.1.jar
Xaeros_Minimap_21.20.0_Fabric_1.17.1.jar
XaerosWorldMap_1.18.1_Fabric_1.17.1.jar
YungsApi-1.17-Fabric-19.jar

**Comment by stashymane** [comment]
Can reproduce the same effect, trying to fix now - seems to only occur when breaking blocks for now
