### ISSUE TITLE
[Optifine] GameOptionsMixin causes crash on startup

### ISSUE THREAD

**Issue by Toilet-Man** [stashymane/extra-sounds#31]
Minecraft: 1.18.1
Mod: 2.2.0 1.18

## Details
Minecraft crashes when the mod is loaded. There is no pop-up message

>Please run the game with `-Dextrasounds.debug=true` added to your Java arguments and attach a log file as well.

did it
[latest.log](https://github.com/stashymane/extra-sounds/files/7794810/latest.log)

((I'm loading the game with Fabric Loader 0.12.11 if that could be the problem))

**Comment by stashymane** [comment]
Optifine incompatibility - Optifine on Fabric is on life support, please use Sodium + Iris instead.

**Comment by stashymane** [comment]
Leaving this open in case anyone wants to fix this, I don't have the time to do it myself at the moment.

**Comment by Toilet-Man** [comment]
Thanks a lot for looking into it

> Optifine incompatibility - Optifine on Fabric is on life support, please use Sodium + Iris instead.

Yeah I know.. the only thing holding me back is support for SEUS PTGI. It works and I know there are fixes that can help but most of the features that I'm interested about don't work with iris + sodium

**Comment by stashymane** [comment]
SoundCategories now makes the mixin that fails injection with Optifine optional. Not the best solution, but for now it will do.

**Comment by Darutan92** [comment]
> SoundCategories now makes the mixin that fails injection with Optifine optional. Not the best solution, but for now it will do.
Where can I download the new version?

**Comment by stashymane** [comment]
I'd recommend waiting for 2.3.0, since that will include it by default and will be fully compatible, but if you're interested to try you can get it from https://modrinth.com/mod/sound-categories
Keep in mind some people have SoundCategories fail to load completely when installing the newer version and I am not exactly sure why yet, as nobody has provided any logs as of now.

**Comment by Darutan92** [comment]
> I'd recommend waiting for 2.3.0, since that will include it by default and will be fully compatible, but if you're interested to try you can get it from https://modrinth.com/mod/sound-categories Keep in mind some people have SoundCategories fail to load completely when installing the newer version and I am not exactly sure why yet, as nobody has provided any logs as of now.

Hello. You recently updated the mod version 1.18+ making Optifine compatible, but the update did not come out on 1.17. I raised this issue (specifically for 1.17) here, it was merged with the current one and closed. Are you going to no longer support ExtaSound for this version?

**Comment by stashymane** [comment]
> > I'd recommend waiting for 2.3.0, since that will include it by default and will be fully compatible, but if you're interested to try you can get it from https://modrinth.com/mod/sound-categories Keep in mind some people have SoundCategories fail to load completely when installing the newer version and I am not exactly sure why yet, as nobody has provided any logs as of now.
> 
> Hello. You recently updated the mod version 1.18+ making Optifine compatible, but the update did not come out on 1.17. I raised this issue (specifically for 1.17) [here](https://github.com/stashymane/extra-sounds/issues/48), it was merged with the current one and closed. Are you going to no longer support ExtaSound for this version?

I'll most likely release one more version for 1.17 and 1.16, but for the future I'm only planning to support the 2 latest versions of Minecraft.

**Comment by Darutan92** [comment]
> I'll most likely release one more version for 1.17 and 1.16, but for the future I'm only planning to support the 2 latest versions of Minecraft.

Thank you, I will hope for the best.
