### ISSUE TITLE
Random Chorus Fruit Growing Sounds

### ISSUE THREAD

**Issue by Sydokiddo** [stashymane/extra-sounds#34]
Minecraft: Fabric Loader 0.12.12 (Minecraft 1.18.1)
Mod: 2.0.2 for 1.18

For whatever reason while playing normally, I occasionally every now and then hear random Chorus Fruit growing sounds playing for some reason. Nothing appears on the subtitles either, although I still hear the sound frequently.

**Comment by stashymane** [comment]
A similar issue has been fixed earlier, but should be okay in 2.0.2 - might be another mod incompatibility. Could you perhaps post your mod list?

**Comment by SkeleBones** [comment]
#24 this other issue is the same as this but this one describes it better.

**Comment by stashymane** [comment]
Closing as unable to reproduce. I may have fixed this issue earlier accidentally, but I cannot get this effect with the same mods as listed in #24. If you still face this bug in 2.3.0, please reopen the issue with a log.
