### ISSUE TITLE
[Feature Request] Add config screen

### ISSUE THREAD

**Issue by alexmozaidze** [stashymane/extra-sounds#35]
I want to disable some sounds but I don't want to mess with resource packs. It would be cool if you added a config screen for toggling some sounds.

**Comment by stashymane** [comment]
You can turn off certain sound categories via the sound volume menu. In-depth customization is too much to put into Minecraft, which is why I left it for resource packs to change. I will eventually finish a tool to make resources easily, however for now you'll need to do so manually.
