### ISSUE TITLE
1.18.1 support?

### ISSUE THREAD

**Issue by sioodmy** [stashymane/extra-sounds#36]
Are there any plans of updating this mod to 1.18.1?

**Comment by stashymane** [comment]
It's right on the download page :)
In general, the mod should support all minor releases of Minecraft, aka the 1.18 version should support 1.18.1, 1.18.2 (if it comes out) and any further ones, unless they mess with the client too much.

![image](https://user-images.githubusercontent.com/4071883/153611486-f24e44fc-1c58-4eef-92c8-82bc82d652ea.png)
