### ISSUE TITLE
Game crashes on launch - MC 1.18.2, v2.2.0

### ISSUE THREAD

**Issue by MaxJW** [stashymane/extra-sounds#38]
Minecraft: 1.18.2
Mod: 2.2.0+1.17

## Details
Minecraft fails to launch with ExtraSounds installed. I've attached the crash file below:
[crash-2022-03-03_13.51.12-client.txt](https://github.com/stashymane/extra-sounds/files/8178341/crash-2022-03-03_13.51.12-client.txt)

**Comment by stashymane** [comment]
Caused by https://github.com/Devan-Kerman/ARRP/issues/57 - waiting for fixed version to be available.

**Comment by stashymane** [comment]
Fixed in 2.2.1.
