### ISSUE TITLE
Inventory Profiles Next Compatibility

### ISSUE THREAD

**Issue by foxinacove** [stashymane/extra-sounds#44]
With the [IPN mod](https://github.com/blackd/Inventory-Profiles), it's possible to hold down Shift and drag the cursor over items, moving said items in the cursor's dragging path to or from an inventory. Currently, this bypasses Extra Sounds and doesn't create any sound. It would be cool to hear a barrage of item moving sounds for this, if that's even possible!

**Comment by stashymane** [comment]
Inventory Profiles skips the item click event and sends an inventory change packet immediately, which is why the sound does not get played. Listening for the packet as well might fix another issue I had to work around where sounds are played multiple times on click. I'll take a look.

**Comment by blackd** [comment]
IPN "simulates clicks" but I Invoke ScreenHandler.onSlotClick instead of Screen.onMouseClick essentially bypassing most of the local processing. As an added bonus this allows me to be compatible with some mods that extend Screen in strange ways.

I guess you can hook in the same place.

**Comment by stashymane** [comment]
Ah, I inject into HandledScreen, so that makes sense. May be that I was referring to another inventory management mod instead. Working on it.
