### ISSUE TITLE
Compatibility issues?

### ISSUE THREAD

**Issue by Konglomneshued** [stashymane/extra-sounds#45]
Currently I am getting no sounds from this mod; I've used it before so I know what it adds and I'm not hearing it.

I have a bunch of mods installed but I'm not crashing so I don't know what's causing this to break.

**Comment by Konglomneshued** [comment]
This mod is incompatible with Resounding.

**Comment by stashymane** [comment]
Regarding the sounds being muffled - that is a Resounding issue. ExtraSounds plays sounds the exact same way Minecraft's UI does, although I don't necessarily like it, as all sounds are positioned - most likely this is why Resounding trips up. For now I think this is an issue that needs to be resolved on their side.
Regarding sounds not playing entirely - I cannot reproduce this. A demo screen recording + logs would be appreciated if you're still facing that issue.

**Comment by stashymane** [comment]
Never mind, I can reproduce this only with Resounding installed. Seems like an issue on their part currently. If you are able to reproduce this with only ExtraSounds installed, I'll reopen this.
