### ISSUE TITLE
Crash when typing in menu text box

### ISSUE THREAD

**Issue by Balin-P** [stashymane/extra-sounds#59]
Minecraft: 1.19
Mod: 2.3.0

## Details
Game crashes when I type a character in any text box on the menu. Seems to mention this mod and Architectury.
[crash-2022-06-13_01.29.10-client.txt](https://github.com/stashymane/extra-sounds/files/8886142/crash-2022-06-13_01.29.10-client.txt)

**Comment by stashymane** [comment]
Of course I didn't catch this bug before release, everything's fine right before I upload :)

**Comment by stashymane** [comment]
Fixed in 2.3.1, already uploaded to Modrinth, once Curse comes back from 504 errors I'll also up there.
