### ISSUE TITLE
[feature request] shift click sound

### ISSUE THREAD

**Issue by SpacEagle17** [stashymane/extra-sounds#6]
It would be nice if shift clicking in an inventory would give a sound.

**Comment by stashymane** [comment]
This was accidentally removed due to a temporary crash workaround. Should be fixed in [this commit](https://github.com/stashymane/extra-sounds/commit/f963ba61b8048846d24efe10624d87ba10f2d390).

**Comment by stashymane** [comment]
And is now fixed in 1.2.0.
