### ISSUE TITLE
Unable to join servers with custom sound events (Minecraft 1.19)

### ISSUE THREAD

**Issue by NoEnd-yt** [stashymane/extra-sounds#63]
## Minecraft and mod versions:
Minecraft: 1.19
Mod: 2.3.1+1.19

## Details:
The game is unable to join servers with custom sound events.
## Expected behavior:
You should be able to join servers with custom sound events.
## How to reproduce:
Join any servers with custom sound events.

## Latest.log:
[latest.log](https://github.com/stashymane/extra-sounds/files/8998190/latest.log)

**Comment by stashymane** [comment]
Resolved in v3, might backport the changes to v2 if the new release takes too long.
