### ISSUE TITLE
Shift clicking doesn't work in only the player inventory

### ISSUE THREAD

**Issue by SpacEagle17** [stashymane/extra-sounds#7]
When shift clicking inside the player inventory no sound is played and when right clicking and dragging to separate the stack no sound is played either (a good sound would be the sound of a deck of carts)
https://user-images.githubusercontent.com/46494907/118473655-8262c880-b70a-11eb-8771-b29dd538767a.mp4

**Comment by SpacEagle17** [comment]
Shift clicking from the player inventory into a crafting table works though

**Comment by stashymane** [comment]
Seems not to work only in the creative inventory, as I tested with survival and everything seemed fine. Working on it.

**Comment by SpacEagle17** [comment]
Ah nice

**Comment by stashymane** [comment]
Since I'm not going to push another release with a small bugfix only the same day, [you can get the dev build from the artifacts here](https://github.com/stashymane/extra-sounds/actions/runs/849655107).
The drag sound is most likely coming on next release.
