### ISSUE TITLE
Crush

### ISSUE THREAD

**Issue by Furious907** [stashymane/extra-sounds#75]
Minecraft: 1.19.2
Mod: ExtraSounds

## Details
Detail what happens here, and why or how it should or should not happen.

crushing wtihout showing minecraft window
[crash-2022-08-20_17.01.48-client.txt](https://github.com/stashymane/extra-sounds/files/9387415/crash-2022-08-20_17.01.48-client.txt)

[how i did understood that problem in this mod.txt](https://github.com/stashymane/extra-sounds/files/9387468/how.i.did.understood.that.problem.in.this.mod.txt)

**PLEASE attach your `latest.log` (and crash log if your game crashes), makes it much easier to troubleshoot, thank you!**
You can also run the game with the `-Dextrasounds.debug=true` Java launch parameter to see more info about what's going on.

**Comment by lonefelidae16** [comment]
#74

**Comment by Furious907** [comment]
> #74

Thanks
