### ISSUE TITLE
Crash when loading up

### ISSUE THREAD

**Issue by DanMeadWasTaken** [stashymane/extra-sounds#76]
Minecraft: [1.19.2]
Mod: [2.3.1]

## Details
Game crashes when loading. Multimc spits out this log which points towards the extra sounds mod, chat sounds specifically causing the crash. Mod list, and more is included in the log.
https://paste.ee/p/ciG1T

**Comment by lonefelidae16** [comment]
the same as #75
see #74

**Comment by DanMeadWasTaken** [comment]
This seems to have fixed it, thank you

**Comment by DanMeadWasTaken** [comment]
New problem ^-^
With this altered version, my sound just doesn't work at all. Youtube plays fine, but when i try to make any sound in minecraft, nothing what so ever.
https://paste.ee/p/WTqRW

**Comment by DanMeadWasTaken** [comment]
Nvm, turns out i am an idiot :D 
Basically, main volume slider was full, but somehow the minecraft application volume slider got turned down. So this one was on me.
