### ISSUE TITLE
[Crash]: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_338 failed

### ISSUE THREAD

**Issue by SpigotDE** [stashymane/extra-sounds#77]
Fabric 1.19.2 - 0.14.9
Extra Sounds 2.3.1

[latest.log](https://gist.github.com/SpigotDE/9dd9dda7f54eb8975248829cc9543925)
[crash-report](https://gist.github.com/SpigotDE/11ccf2d110593a9e20582b68cc914690)

**Comment by lonefelidae16** [comment]
Please check the issue board before creating a new one.

the same as #75, #76
see #74
