### ISSUE TITLE
Do not register sounds

### ISSUE THREAD

**Issue by Binero** [stashymane/extra-sounds#79]
This is a client-side modification. Minecraft does not require sounds that are client-only to be registered to play them. Simply removing the register call while keeping everything else intact should work fine.

This would make Extra-Sounds compatible with servers that have custom sounds of themselves. Right now the game will refuse to connect to those servers because the server has a different registry.

**Comment by stashymane** [comment]
Done in v3, the way I was working on this initially made it seem like events have to be registered before they can be used. Small oversight.
