### ISSUE TITLE
Crash when loaded with a Automated Crafting mod (https://www.curseforge.com/minecraft/mc-mods/automated-crafting)

### ISSUE THREAD

**Issue by spunchbop121** [stashymane/extra-sounds#81]
Minecraft: [version]
Mod: [version]

## Details
Detail what happens here, and why or how it should or should not happen.

**PLEASE attach your `latest.log` (and crash log if your game crashes), makes it much easier to troubleshoot, thank you!**
You can also run the game with the `-Dextrasounds.debug=true` Java launch parameter to see more info about what's going on.

**Comment by stashymane** [comment]
No Minecraft or mod version, no logs. Please attach these at minimum and I will reopen the issue, thank you.
