### ISSUE TITLE
[Meta] Curseforge license doesn't match Github license

### ISSUE THREAD

**Issue by Thanos1716** [stashymane/extra-sounds#85]
As stated, on curseforge the license for this project is ARR but on github its listed as CC0 1.0 Universal, which in my opinion is a great license, so I was originally disappointed when seeing that it was ARR on Curseforge
I think it may help to avoid confusion if you could change the license on Curseforge to reflect this repository :)

**Comment by stashymane** [comment]
Forgot to change it on CF, the default presets aren't that great :(
Copied the CC0 license to it now
