### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Electricurmom** [stashymane/extra-sounds#87]
Minecraft: [1.19.2 Fabric]
Mod: [Extra Sounds]

## Details
[latest.log](https://github.com/stashymane/extra-sounds/files/9910381/latest.log)

i tried to open the game after adding this mod and it crashes(optfine+optifabric)

**PLEASE attach your `latest.log` (and crash log if your game crashes), makes it much easier to troubleshoot, thank you!**
You can also run the game with the `-Dextrasounds.debug=true` Java launch parameter to see more info about what's going on.

**Comment by stashymane** [comment]
Optifabric issue, working on seeing what I can do.
Tracked on #69
