### ISSUE TITLE
Shift clicking when inventory is full while crafting creates sound

### ISSUE THREAD

**Issue by SpacEagle17** [stashymane/extra-sounds#9]
https://user-images.githubusercontent.com/46494907/119172934-cc2f1400-ba66-11eb-8d5a-fb5a67a67bea.mp4

**Comment by stashymane** [comment]
Currently, checking for any open inventory slots is too complicated to implement without it being a gross hack (because Mojang). Might work on this after changing when the click is detected, however for now this will remain as-is.
